# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: AzureMonitorAlerts@0
      inputs:
        azureSubscription: 'Free Trial(226e94f1-cab8-45b1-b154-b9f9e767cce8)'
        ResourceGroupName: 'NetworkWatcherRG'
        ResourceType: 'Microsoft.Insights/components'
        ResourceName: '<YourResourceName>'  # Ensure this is filled with the correct resource name
        AlertRules: 'metric'  # Change 'monitor' to 'metric' for metric alerts
        NotifyServiceOwners: true
        NotifyEmails: 'deepak.deepu4490@gmail.com'
    - task: AzureMonitorAlerts@0
      inputs:
        azureSubscription: 'Free Trial(226e94f1-cab8-45b1-b154-b9f9e767cce8)'
        ResourceGroupName: 'NetworkWatcherRG'
        ResourceType: 'Microsoft.Insights/components'
        ResourceName: '<YourResourceName>'
        AlertRules: 'activityLog'
        NotifyServiceOwners: true
        NotifyEmails: 'deepak.deepu4490@gmail.com'
    - task: AzureMonitorAlerts@0
      inputs:
        azureSubscription: 'Free Trial(226e94f1-cab8-45b1-b154-b9f9e767cce8)'
        ResourceGroupName: 'NetworkWatcherRG'
        ResourceType: 'Microsoft.Insights/components'
        ResourceName: '<YourResourceName>'
        AlertRules: 'serviceHealth'
        NotifyServiceOwners: true
        NotifyEmails: 'deepak.deepu4490@gmail.com'
    
