apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmpapp
  labels:
    app: gmpapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gmpapp
  template:
    metadata:
      labels:
        app: gmpapp
    spec:
      containers:
        - name: gmpcontainer
          image: gmpcontainer.azurecr.io/greetingmessageproject:latest
          imagePullPolicy: Always
          ports:  # Correct indentation here
            - containerPort: 8080
