apiVersion: v1
kind: Service
metadata:
  name: gmp-service
  namespace: dev
spec:
  selector:
    app: gmp-app
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 8080  # Container port
  type: LoadBalancer  # For external access
